spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:[::1]:9092}
  datasource:
    url: jdbc:postgresql://[::1]:5436/notification_db
    username: notification_user
    password: notification_password
