CREATE TABLE theaters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    city VARCHAR(100) NOT NULL,
    address VARCHAR(1000) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE screens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    total_seats INTEGER NOT NULL CHECK (total_seats > 0),
    active BOOLEAN NOT NULL,
    theater_id BIGINT NOT NULL REFERENCES theaters(id),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE shows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL REFERENCES movies(id),
    screen_id BIGINT NOT NULL REFERENCES screens(id),
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT shows_time_order CHECK (start_time < end_time)
);

-- Theater screen listing and the theater -> screen -> show search path.
CREATE INDEX idx_screens_theater_id ON screens (theater_id);
-- Movie/date search and FK checks when a movie is deleted.
CREATE INDEX idx_shows_movie_start_time ON shows (movie_id, start_time);
-- Theater searches via screens, screen scheduling queries, and FK checks.
CREATE INDEX idx_shows_screen_start_time ON shows (screen_id, start_time);
-- Date-only searches and stable chronological pagination.
CREATE INDEX idx_shows_start_time_id ON shows (start_time, id);
