CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_reference VARCHAR(36) NOT NULL UNIQUE,
    show_id BIGINT NOT NULL CHECK (show_id > 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'CONFIRMED', 'EXPIRED', 'CANCELLED')),
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE show_seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id BIGINT NOT NULL CHECK (show_id > 0),
    seat_number VARCHAR(20) NOT NULL CHECK (seat_number ~ '^[A-Z0-9-]{1,20}$'),
    status VARCHAR(20) NOT NULL CHECK (status IN ('AVAILABLE', 'HELD', 'BOOKED')),
    version BIGINT NOT NULL DEFAULT 0,
    current_reservation_id BIGINT REFERENCES reservations(id),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_show_seat UNIQUE (show_id, seat_number),
    CONSTRAINT ck_seat_owner CHECK (
        (status = 'AVAILABLE' AND current_reservation_id IS NULL) OR
        (status IN ('HELD', 'BOOKED') AND current_reservation_id IS NOT NULL)
    )
);

-- Immutable historical membership. A released seat can appear in later reservations.
CREATE TABLE reservation_seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL REFERENCES reservations(id),
    seat_id BIGINT NOT NULL REFERENCES show_seats(id),
    CONSTRAINT uq_reservation_seat UNIQUE (reservation_id, seat_id)
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_reference VARCHAR(36) NOT NULL UNIQUE,
    reservation_id BIGINT NOT NULL UNIQUE REFERENCES reservations(id),
    show_id BIGINT NOT NULL CHECK (show_id > 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED')),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

-- Show/status browsing in stable ID order; show/seat-number uniqueness has its own index.
CREATE INDEX idx_show_seats_show_status_id ON show_seats(show_id, status, id);
-- FK checks when a referenced Reservation is changed/deleted.
CREATE INDEX idx_show_seats_current_reservation ON show_seats(current_reservation_id);
-- Reservation membership lookups use uq_reservation_seat; reverse FK checks use this index.
CREATE INDEX idx_reservation_seats_seat ON reservation_seats(seat_id);
-- Bounded scheduled cleanup of only ACTIVE reservations.
CREATE INDEX idx_reservations_expiration ON reservations(expires_at, id) WHERE status = 'ACTIVE';
