CREATE TABLE consumed_events (
    event_id UUID PRIMARY KEY,
    consumed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL REFERENCES consumed_events(event_id),
    booking_reference VARCHAR(36) NOT NULL,
    subject VARCHAR(100) NOT NULL,
    channel VARCHAR(10) NOT NULL CHECK (channel IN ('EMAIL', 'SMS')),
    status VARCHAR(10) NOT NULL CHECK (status IN ('PENDING', 'SENT')),
    recipient VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    sent_at TIMESTAMPTZ,
    CONSTRAINT uq_notification_event_channel UNIQUE(event_id, channel),
    CONSTRAINT ck_notification_sent CHECK ((status = 'SENT') = (sent_at IS NOT NULL))
);
CREATE INDEX idx_notifications_booking ON notifications(booking_reference);
